services:
  - type: web
    name: impact_web_360
    env: php
    plan: free
    deployCommand: "composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan db:seed --force"
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:CVZAq3AKESMGZSuutyybpOicT8693kpiMcGfTrQGpEg=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d2aj8imuk2gs73a54uo0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: impact_web_360_final_jkme
      - key: DB_USERNAME
        value: impact_web_360_final_jkme_user
      - key: DB_PASSWORD
        value: et8oXvtjcyfShcdLgN2TD8ilAr6JUq3K
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: kounoumarcus@gmail.com
      - key: MAIL_PASSWORD
        value: "rmvy gjjq nibn ojeq"
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: kounoumarcus@gmail.com
      - key: MAIL_FROM_NAME
        value: Laravel
    autoDeploy: true